from pathlib import Path

ADDON_DIR = Path(__file__).parent
RESOURCES_DIR = ADDON_DIR / "Resources"

# Game settings
INITIAL_MONEY = 1500
INITIAL_CELL_SIZE = 100
STATS_PANEL_WIDTH = 250
GRID_SIZE = 4
MAX_GROWTH = 150
GROWTH_RATE = 3

# Growth ranges by animal (min, max) per reviewed card
CHICKEN_GROWTH_RANGE = (1, 4)
PIG_GROWTH_RANGE = (0, 3)
COW_GROWTH_RANGE = (0, 2)
HORSE_GROWTH_RANGE = (0, 1)

# Production chances
CHICKEN_PRODUCTION_CHANCE = 0.10
COW_PRODUCTION_CHANCE = 0.02
PIG_PRODUCTION_CHANCE = 0.01

# Production values
CHICKEN_MIN_PRODUCTION = 5
CHICKEN_MAX_PRODUCTION = 10
COW_PRODUCTION_VALUE = 50

# Pig sale bonus from breed level
PIG_SALE_BONUS_PER_LEVEL = 0.015

# Field prices
BASE_FIELD_PRICE = 500
FIELD_PRICE_MULTIPLIER = 1.5

VERSION = "1.6.0"
